[build]
  command = "pnpm build && pnpm --dir site build"
  publish = "site/out"

[build.environment]
  NODE_VERSION = "24.16.0"
  NETLIFY = "true"

# These take effect in production and should match the redirects in next.config.js
[[redirects]]
  from = "/"
  to = "/docs/introduction"

[[redirects]]
  from = "/docs"
  to = "/docs/introduction"

[[redirects]]
  from = "/community"
  to = "/docs/community"
