/** @jsxImportSource theme-ui */
import { render } from '@testing-library/react'
import Head from 'next/head'
import Image from 'next/image'
import React, { useState } from 'react'

// const test = {
//   MyComponent$9() {
//     return <div css={{ color: 'red' }}>red</div>
//   }
// }

export default function Home() {
  const [count, setCount] = useState(true)

  // const el = test.MyComponent$9()

  return (
    <div>
      <Head>
        <title>Next.js Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Next.js Playground</h1>
      <MyComponent$9 />
    </div>
  )
}
