import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  function renderSpan() {
    return <span css={{ color: 'orchid' }}>Orchid2</span>
  }

  return (
    <div>
      <Head>
        <title>Next.js Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Next.js Playground</h1>
      {[0].map(() => (
        <div css={{ color: 'blue' }} />
      ))}
    </div>
  )
}
