import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div css={{ padding: '2rem' }}>
      <Head>
        <title>Next.js Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 css={{ marginTop: 0 }}>Next.js Playground</h1>
      <div css={{ color: 'orchid' }}>Some colored text</div>
    </div>
  )
}
