name: 'CI setup'
inputs:
  node-version:
    description: 'Node.js version passed to setup-node'
    required: false
    default: 16.x
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn

    - name: Install Dependencies
      run: yarn --immutable
      shell: bash
