// flow-typed signature: 47a1ce76579bcf60e33bc03fcf5c8762
// flow-typed version: <<STUB>>/gatsby_v^1.9.100/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby' {
  declare module.exports: any
}
// eslint-disable-next-line no-unused-vars
declare var graphql: Function
