blank_issues_enabled: true
contact_links:
  - name: 🤔 Support question
    url: https://stackoverflow.com/questions/ask?tags=emotion
    about: Issues are dedicated to feature requests and bugs, if you have questions, please use Stack Overflow.
