var la=function ba(ca){function S(b,c,d,m){for(var a=0,h=0,k=0,f=0,l,n,e,v=0,z=0,A=0,x=0,t=l=0,q=0,p=0,w=n=0,H=0,B=d.length,I=B-1,u,g="",r="",R="",K="",E;p<B;){e=d.charCodeAt(p);if(0===h+f+k+a){if(p===I&&(0<n&&(g=g.replace(M,"")),0<g.trim().length)){switch(e){case 32:case 9:case 59:case 13:case 10:break;default:g+=d.charAt(p)}e=59}if(1===w)switch(e){case 123:case 44:w=0;break;case 9:case 13:case 10:case 32:break;default:p--,e=59}switch(e){case 123:g=g.trim();l=g.charCodeAt(0);x=1;for(t=++p;p<B;){e=
  d.charCodeAt(p);switch(e){case 123:x++;break;case 125:x--}if(0===x)break;p++}e=d.substring(t,p);0===l&&(l=(g=g.replace(ma,"").trim()).charCodeAt(0));switch(l){case 64:0<n&&(g=g.replace(M,""));n=g.charCodeAt(1);switch(n){case 100:case 109:case 115:q=c;break;default:q=T}e=S(c,q,e,n);t=e.length;0<U&&0===t&&(t=g.length);0<C&&(q=da(T,g,H),E=L(3,e,q,c,F,y,t,n),g=q.join(""),void 0!==E&&0===(t=(e=E.trim()).length)&&(n=0,e=""));if(0<t)switch(n){case 115:g=g.replace(na,oa);case 100:case 109:e=g+"{"+e+"}";break;
  case 107:g=g.replace(pa,"$1 $2"+(0<N?O:""));e=g+"{"+e+"}";e="@"+(0<P?"-webkit-"+e+"@"+e:e);break;default:e=g+e}else e="";break;default:e=S(c,da(c,g,H),e,m)}R+=e;t=H=n=q=w=l=0;g="";e=d.charCodeAt(++p);break;case 125:case 59:g=(0<n?g.replace(M,""):g).trim();if(1<g.length)switch(0===q&&(l=g.charCodeAt(0),(45===l||96<l&&123>l)&&g.indexOf(" ")&&(g=g.replace(" ",":"))),0<C&&void 0!==(E=L(1,g,c,b,F,y,r.length,m))&&0===(g=E.trim()).length&&(g="\x00\x00"),l=g.charCodeAt(0),n=g.charCodeAt(1),l+n){case 0:break;
  case 169:case 163:K+=g+d.charAt(p);break;default:r+=0<q?ea(g,l,n,g.charCodeAt(2)):g+";"}H=n=q=w=l=0;g="";e=d.charCodeAt(++p)}}switch(e){case 13:case 10:if(0===h+f+k+a+fa)switch(A){case 41:case 39:case 34:case 64:case 126:case 62:case 42:case 43:case 47:case 45:case 58:case 44:case 59:case 123:case 125:break;default:0<q&&(w=1)}47===h&&(h=0);0<C*ha&&L(0,g,c,b,F,y,r.length,m);y=1;F++;break;case 59:case 125:if(0===h+f+k+a){y++;break}default:y++;u=d.charAt(p);switch(e){case 9:case 32:if(0===f+a)switch(v){case 44:case 58:case 9:case 32:u=
  "";break;default:32!==e&&(u=" ")}break;case 0:u="\\0";break;case 12:u="\\f";break;case 11:u="\\v";break;case 38:0===f+h+a&&0<D&&(n=H=1,u="\f"+u);break;case 108:if(0===f+h+a+J&&0<q)switch(p-q){case 2:112===v&&58===d.charCodeAt(p-3)&&(J=v);case 8:111===z&&(J=z)}break;case 58:0===f+h+a&&(q=p);break;case 44:0===h+k+f+a&&(n=1,u+="\r");break;case 34:0===h&&(f=f===e?0:0===f?e:f,p===I&&(I++,B++));break;case 39:0===h&&(f=f===e?0:0===f?e:f,p===I&&(I++,B++));break;case 91:0===f+h+k&&a++;break;case 93:0===f+
  h+k&&a--;break;case 41:0===f+h+a&&(p===I&&(I++,B++),k--);break;case 40:if(0===f+h+a){if(0===l)switch(2*v+3*z){case 533:break;default:x=0,l=1}k++}break;case 64:0===h+k+f+a+q+t&&(t=1);break;case 42:case 47:if(!(0<f+a+k))switch(h){case 0:switch(2*e+3*d.charCodeAt(p+1)){case 235:h=47;break;case 220:h=42}break;case 42:47===e&&42===v&&(u="",h=0)}}if(0===h){if(0===D+f+a+t&&107!==m&&59!==e)switch(e){case 44:case 126:case 62:case 43:case 41:case 40:if(0===l){switch(v){case 9:case 32:case 10:case 13:u+="\x00";
  break;default:u="\x00"+u+(44===e?"":"\x00")}n=1}else switch(e){case 40:l=++x;break;case 41:0===(l=--x)&&(n=1,u+="\x00")}break;case 32:switch(v){case 0:case 123:case 125:case 59:case 44:case 12:case 9:case 32:case 10:case 13:break;default:0===l&&(n=1,u+="\x00")}}g+=u;32!==e&&(A=e)}}z=v;v=e;p++}t=r.length;0<U&&0===t&&0===R.length&&0===c[0].length===!1&&(109!==m||1===c.length&&(0<D?G:Q)===c[0])&&(t=c.join(",").length+2);if(0<t){if(0===D&&107!==m){d=0;a=c.length;for(h=Array(a);d<a;++d){v=c[d].split(qa);
  z="";A=0;for(B=v.length;A<B;++A)if(!(0===(x=(f=v[A]).length)&&1<B)){p=z.charCodeAt(z.length-1);H=f.charCodeAt(0);k="";if(0!==A)switch(p){case 42:case 126:case 62:case 43:case 32:case 40:break;default:k=" "}switch(H){case 38:f=k+G;case 126:case 62:case 43:case 32:case 41:case 40:break;case 91:f=k+f+G;break;case 58:switch(2*f.charCodeAt(1)+3*f.charCodeAt(2)){case 530:if(0<V){f=k+f.substring(8,x-1);break}default:if(1>A||1>v[A-1].length)f=k+G+f}break;case 44:k="";default:f=1<x&&0<f.indexOf(":")?k+f.replace(ra,
  "$1"+G+"$2"):k+f+G}z+=f}h[d]=z.replace(M,"").trim()}c=h}q=c;if(0<C&&(E=L(2,r,q,b,F,y,t,m),void 0!==E&&0===(r=E).length))return K+r+R;r=q.join(",")+"{"+r+"}";if(0<P*J){switch(J){case 111:r=r.replace(sa,":-moz-$1")+r;break;case 112:r=r.replace(W,"::-webkit-input-$1")+r.replace(W,"::-moz-$1")+r.replace(W,":-ms-input-$1")+r}J=0}}return K+r+R}function da(b,c,d){var m=c.trim().split(ta);c=m;var a=m.length,h=b.length;switch(h){case 0:case 1:var k=0;for(b=0===h?"":b[0]+" ";k<a;++k)c[k]=ia(b,c[k],d,h).trim();
  break;default:var f=k=0;for(c=[];k<a;++k)for(var l=0;l<h;++l)c[f++]=ia(b[l]+" ",m[k],d,h).trim()}return c}function ia(b,c,d,m){var a=c.charCodeAt(0);33>a&&(a=(c=c.trim()).charCodeAt(0));switch(a){case 38:switch(D+m){case 0:case 1:if(0===b.trim().length)break;default:return c.replace(K,"$1"+b.trim())}break;case 58:switch(c.charCodeAt(1)){case 103:if(0<V&&0<D)return c.replace(ua,"$1").replace(K,"$1"+Q);break;default:return b.trim()+c}default:if(0<d*D&&0<c.indexOf("\f"))return c.replace(K,(58===b.charCodeAt(0)?
  "":"$1")+b.trim())}return b+c}function ea(b,c,d,m){var a=b+";";c=2*c+3*d+4*m;if(944===c){c=a;d=c.length;m=c.indexOf(":",9)+1;a=c.substring(0,m).trim();d=c.substring(m,d-1).trim();b="";if(45!==c.charCodeAt(9)){c=d.split(va);var h=0;m=0;for(d=c.length;h<d;m=0,++h){for(var k=c[h],f=k.split(wa);k=f[m];){var l=k.charCodeAt(0);if(1===N&&(64<l&&90>l||96<l&&123>l||95===l||45===l&&45!==k.charCodeAt(1)))switch(isNaN(parseFloat(k))+(-1!==k.indexOf("("))){case 1:switch(k){case "infinite":case "alternate":case "backwards":case "running":case "normal":case "forwards":case "both":case "none":case "linear":case "ease":case "ease-in":case "ease-out":case "ease-in-out":case "paused":case "reverse":case "alternate-reverse":case "inherit":case "initial":case "unset":case "step-start":case "step-end":break;
  default:k+=O}}f[m++]=k}b+=(0===h?"":",")+f.join(" ")}}else b+=110===c.charCodeAt(10)?d+(1===N?O:""):d;b=a+b+";";a=0<P?"-webkit-"+b+b:b}else if(0<P)switch(c){case 969:a="-webkit-"+a.replace(xa,"-webkit-$1")+a;break;case 951:a="-webkit-"+a+a;break;case 963:110===a.charCodeAt(5)&&(a="-webkit-"+a+a);break;case 978:a="-webkit-"+a+"-moz-"+a+a;break;case 1019:case 983:a="-webkit-"+a+"-moz-"+a+"-ms-"+a+a;break;case 883:45===a.charCodeAt(8)&&(a="-webkit-"+a+a);break;case 932:a="-webkit-"+a+"-ms-"+a+a;break;
  case 964:a="-webkit-"+a+"-ms-flex-"+a+a;break;case 1023:b=a.substring(a.indexOf(":",15)).replace("flex-","");a="-webkit-box-pack"+b+"-webkit-"+a+"-ms-flex-pack"+b+a;break;case 1017:if(-1===a.indexOf("sticky",9))break;case 975:d=(a=b).length-10;b=(33===a.charCodeAt(d)?a.substring(0,d):a).substring(b.indexOf(":",7)+1).trim();switch(c=b.charCodeAt(0)+(b.charCodeAt(7)|0)){case 203:if(111>b.charCodeAt(8))break;case 115:a=a.replace(b,"-webkit-"+b)+";"+a;break;case 207:case 102:a=a.replace(b,"-webkit-"+
  (102<c?"inline-":"")+"box")+";"+a.replace(b,"-webkit-"+b)+";"+a.replace(b,"-ms-"+b+"box")+";"+a}a+=";";break;case 938:if(45===a.charCodeAt(5))switch(a.charCodeAt(6)){case 105:b=a.replace("-items","");a="-webkit-"+a+"-webkit-box-"+b+"-ms-flex-"+b+a;break;case 115:a="-webkit-"+a+"-ms-flex-item-"+a.replace("-self","")+a;break;default:a="-webkit-"+a+"-ms-flex-line-pack"+a.replace("align-content","")+a}break;case 1005:ya.test(a)&&(a=a.replace(ja,":-webkit-")+a.replace(ja,":-moz-")+a);break;case 953:0<
  (d=a.indexOf("-content",9))&&(b=a.substring(d-3),a="width:-webkit-"+b+"width:-moz-"+b+"width:"+b);break;case 1015:if(45!==b.charCodeAt(9))break;case 962:a="-webkit-"+a+(102===a.charCodeAt(5)?"-ms-"+a:"")+a;211===d+m&&105===a.charCodeAt(13)&&0<a.indexOf("transform",10)&&(a=a.substring(0,a.indexOf(";",27)+1).replace(za,"$1-webkit-$2")+a);break;case 1E3:b=a.substring(13).trim();d=b.indexOf("-")+1;switch(b.charCodeAt(0)+b.charCodeAt(d)){case 226:b=a.replace(X,"tb");break;case 232:b=a.replace(X,"tb-rl");
  break;case 220:b=a.replace(X,"lr");break;default:return a}a="-webkit-"+a+"-ms-"+b+a}return a}function oa(b,c){var d=ea(c,c.charCodeAt(0),c.charCodeAt(1),c.charCodeAt(2));return d!==c+";"?d.replace(Aa,"or($1)").substring(2):"("+c+")"}function L(b,c,d,m,a,h,k,f){for(var l=0,n=c,e;l<C;++l)switch(e=Y[l].call(w,b,n,d,m,a,h,k,f)){case void 0:case !1:case !0:case null:break;default:n=e}switch(n){case void 0:case !1:case !0:case null:case c:break;default:return n}}function Z(b){switch(b){case void 0:case null:C=
  Y.length=0;break;default:switch(b.constructor){case Array:for(var c=0,d=b.length;c<d;++c)Z(b[c]);break;case Function:Y[C++]=b;break;case Boolean:ha=!!b|0}}return Z}function aa(b){for(var c in b){var d=b[c];switch(c){case "keyframe":N=d|0;break;case "global":V=d|0;break;case "cascade":D=d|0;break;case "compress":ka=d|0;break;case "prefix":P=d|0;break;case "semicolon":fa=d|0;break;case "preserve":U=d|0}}return aa}function w(b,c){if(void 0!==this&&this.constructor===w)return ba(b);var d=b,m=d.charCodeAt(0);
  33>m&&(m=(d=d.trim()).charCodeAt(0));0<N&&(O=d.replace(Ba,91===m?"":"-"));m=1;1===D?Q=d:G=d;d=[Q];if(0<C){var a=L(-1,c,d,d,F,y,0,0);void 0!==a&&"string"===typeof a&&(c=a)}var h=S(T,d,c,0);0<C&&(a=L(-2,h,d,d,F,y,h.length,0),void 0!==a&&"string"!==typeof(h=a)&&(m=0));G=Q=O="";J=0;y=F=1;return 0===ka*m?h:h.replace(M,"").replace(Ca,"").replace(Da,"$1").replace(Ea,"$1").replace(Fa," ")}var ma=/^\0+/g,M=/[\0\r\f]/g,ja=/: */g,ya=/zoo|gra/,za=/([,: ])(transform)/g,va=/,+\s*(?![^(]*[)])/g,wa=/ +\s*(?![^(]*[)])/g,
  qa=/ *[\0] */g,ta=/,\r+?/g,K=/([\t\r\n ])*\f?&/g,ua=/:global\(((?:[^\(\)\[\]]*|\[.*\]|\([^\(\)]*\))*)\)/g,Ba=/\W+/g,pa=/@(k\w+)\s*(\S*)\s*/,W=/::(place)/g,sa=/:(read-only)/g,Ca=/\s+(?=[{\];=:>])/g,Da=/([[}=:>])\s+/g,Ea=/(\{[^{]+?);(?=\})/g,Fa=/\s{2,}/g,ra=/([^\(])(:+) */g,X=/[svh]\w+-[tblr]{2}/,xa=/([\w-]+t\()/g,na=/\(\s*([^]*?)\s*\)/g,Aa=/([^]*?);/g,y=1,F=1,J=0,D=1,P=1,V=1,ka=0,fa=0,U=0,T=[],Y=[],C=0,ha=0,N=1,O="",G="",Q="";w.use=Z;w.set=aa;void 0!==ca&&aa(ca);return w};
export default la