declare let unitlessKeys: {
  readonly animationIterationCount: 1
  readonly borderImageOutset: 1
  readonly borderImageSlice: 1
  readonly borderImageWidth: 1
  readonly boxFlex: 1
  readonly boxFlexGroup: 1
  readonly boxOrdinalGroup: 1
  readonly columnCount: 1
  readonly columns: 1
  readonly flex: 1
  readonly flexGrow: 1
  readonly flexPositive: 1
  readonly flexShrink: 1
  readonly flexNegative: 1
  readonly flexOrder: 1
  readonly gridRow: 1
  readonly gridRowEnd: 1
  readonly gridRowSpan: 1
  readonly gridRowStart: 1
  readonly gridColumn: 1
  readonly gridColumnEnd: 1
  readonly gridColumnSpan: 1
  readonly gridColumnStart: 1
  readonly msGridRow: 1
  readonly msGridRowSpan: 1
  readonly msGridColumn: 1
  readonly msGridColumnSpan: 1
  readonly fontWeight: 1
  readonly lineHeight: 1
  readonly opacity: 1
  readonly order: 1
  readonly orphans: 1
  readonly tabSize: 1
  readonly widows: 1
  readonly zIndex: 1
  readonly zoom: 1
  readonly WebkitLineClamp: 1
  readonly fillOpacity: 1
  readonly floodOpacity: 1
  readonly stopOpacity: 1
  readonly strokeDasharray: 1
  readonly strokeDashoffset: 1
  readonly strokeMiterlimit: 1
  readonly strokeOpacity: 1
  readonly strokeWidth: 1
}
export default unitlessKeys
