name: Release

on:
  push:
    branches:
      - main
      - next

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
  queue: max

permissions: {}

jobs:
  select-mode:
    name: Select Mode
    runs-on: ubuntu-latest
    timeout-minutes: 20
    outputs:
      mode: ${{ steps.select-mode.outputs.mode }}
      publish-plan-artifact-id: ${{ steps.select-mode.outputs.publish-plan-artifact-id }}
    permissions:
      contents: read
    steps:
      - uses: $/.github/actions/ci-setup

      - name: Select mode
        id: select-mode
        uses: changesets/action/select-mode@22ccf9aa43179fe9e27dc62e575971d28cce197c # v2.0.0

  version:
    name: Version
    needs: select-mode
    if: needs.select-mode.outputs.mode == 'version'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: $/.github/actions/ci-setup

      - name: Create or update release pull request
        uses: changesets/action/version@22ccf9aa43179fe9e27dc62e575971d28cce197c # v2.0.0
        with:
          script: pnpm version-packages

  pack:
    name: Pack
    needs: select-mode
    if: needs.select-mode.outputs.mode == 'publish'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    outputs:
      pack-dir-artifact-id: ${{ steps.pack.outputs.pack-dir-artifact-id }}
    permissions:
      contents: read
    steps:
      - uses: $/.github/actions/ci-setup

      - name: Build
        run: pnpm build

      - name: Pack
        id: pack
        uses: changesets/action/pack@22ccf9aa43179fe9e27dc62e575971d28cce197c # v2.0.0
        with:
          publish-plan-artifact-id: ${{ needs.select-mode.outputs.publish-plan-artifact-id }}

  publish:
    name: Publish
    needs: pack
    runs-on: ubuntu-latest
    environment: npm
    timeout-minutes: 20
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: $/.github/actions/ci-setup

      - name: Publish to npm
        uses: changesets/action/publish@22ccf9aa43179fe9e27dc62e575971d28cce197c # v2.0.0
        with:
          pack-dir-artifact-id: ${{ needs.pack.outputs.pack-dir-artifact-id }}
